const puppeteer = require('puppeteer');

class PdfService {
  async generateWardReport(wardData) {
    const browser = await puppeteer.launch({
      headless: 'new',
      args: ['--no-sandbox', '--disable-setuid-sandbox']
    });

    try {
      const page = await browser.newPage();

      // HTML Template for the PDF
      const htmlContent = `
        <!DOCTYPE html>
        <html>
        <head>
          <style>
            body { font-family: 'Helvetica Neue', Helvetica, Arial, sans-serif; padding: 40px; color: #333; }
            h1 { color: #1e3a8a; border-bottom: 2px solid #1e3a8a; padding-bottom: 10px; }
            .metric-grid { display: flex; flex-wrap: wrap; gap: 20px; margin-top: 30px; }
            .metric-card { background: #f8fafc; border: 1px solid #e2e8f0; border-radius: 8px; padding: 20px; width: calc(50% - 10px); box-sizing: border-box; }
            .metric-title { font-size: 14px; color: #64748b; text-transform: uppercase; letter-spacing: 1px; }
            .metric-value { font-size: 32px; font-weight: bold; color: #0f172a; margin-top: 10px; }
            .footer { margin-top: 50px; font-size: 12px; color: #94a3b8; text-align: center; border-top: 1px solid #e2e8f0; padding-top: 20px; }
          </style>
        </head>
        <body>
          <h1>Community Hero: Ward ${wardData.wardId} Monthly Report</h1>
          <p>Generated on: ${new Date().toLocaleDateString()}</p>
          
          <div class="metric-grid">
            <div class="metric-card">
              <div class="metric-title">Issues Per Capita</div>
              <div class="metric-value">${wardData.issuesPerCapita}</div>
            </div>
            <div class="metric-card">
              <div class="metric-title">Avg Resolution Time</div>
              <div class="metric-value">${wardData.resolutionTimeAvgDays} Days</div>
            </div>
            <div class="metric-card">
              <div class="metric-title">Citizen Satisfaction</div>
              <div class="metric-value">${wardData.citizenSatisfactionScore}%</div>
            </div>
            <div class="metric-card">
              <div class="metric-title">Seasonal Readiness</div>
              <div class="metric-value">${wardData.seasonalReadinessScore}/100</div>
            </div>
          </div>

          <div class="footer">
            Official Municipal Analytics Report | Automatically generated by Community Hero
          </div>
        </body>
        </html>
      `;

      await page.setContent(htmlContent, { waitUntil: 'networkidle0' });
      
      const pdfBuffer = await page.pdf({
        format: 'A4',
        printBackground: true,
        margin: { top: '20px', right: '20px', bottom: '20px', left: '20px' }
      });

      return pdfBuffer;

    } catch (error) {
      console.error('PDF Generation Failed:', error);
      throw error;
    } finally {
      await browser.close();
    }
  }
}

module.exports = new PdfService();
